#!/bin/sh

if [ -d munin-scripts ]
then
  cd munin-scripts
  for script in `ls`
  do
    if [ -x "$script" ]
    then
      echo "<<<munin-$script>>>"
      ./$script
      ./$script config
    fi
  done
  cd ..
fi

