#!/bin/sh

# Unbound statistics
# (c) 2012, Tom Laermans for Observium (www.observium.org)

# Required server configuration:
#
#         statistics-cumulative: yes  
#         extended-statistics: yes 

unboundctl=`which unbound-control`

if [ $? -eq 0 ]
then
  echo '<<<unbound>>>'
  $unboundctl stats
fi
