#!/bin/bash

echo "Linking the agent modules...";
if ! [ -e "/usr/lib/check_mk_agent/local" ]; then
	mkdir "/usr/lib/check_mk_agent/local";
fi;
ln -s /usr/share/observium-agent/agent-local/* /usr/lib/check_mk_agent/local/;

# Ask to link munin plugins
if [ -e "/etc/munin/plugins" ]; then
	echo -n "Link munin plugins for Observium<->Munin integration? [Y/n]: ";
	read link_munin;
	if [ "$link_munin" = "y" || "$link_munin" = "Y" ]; then
		echo "Linking munin plugins folder /etc/munin/plugins...";
		ln -s /etc/munin/plugins /usr/lib/check_mk_agent/local/munin-scripts;
	else
		echo "Ignoring munin plugins";
	fi;
fi;

# Restart xinetd
service xinetd restart
